fn foo() {
  self; // expect error
}
